apiVersion: v1
kind: Service
metadata:
  name: gchat-alerts
  namespace: monitoring
spec:
  selector:
    app: gchat-alerts
  type: ClusterIP        
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80