---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gchat-alerts
  namespace: monitoring
  labels:
    app: gchat-alerts
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gchat-alerts
  template:
    metadata:
      labels:
        app: gchat-alerts
    spec:
      containers:
        - name: gchat-alerts-container
          image: msr.uabc.edu.mx/dit/gchat-alerts
          imagePullPolicy: Always          
          ports:
            - containerPort: 80